### ISSUE TITLE
Warn about non polyfill-able features

### ISSUE THREAD

**Issue by giuseppeg** [jonathantneal/css-db#10]
Awesome initiative! (If only the W3C process was as fast as the TC39 one :p

It would be wise to add warnings for non polyfill-able features like custom properties. 
The PostCSS plugins only add syntax support but their dynamic nature makes it impossible to transpile them to static css :)

**Comment by jonathantneal** [comment]
I’m not sure where to add these notes so a PR is welcome.

**Comment by jonathantneal** [comment]
Hey, I’m going to give this another week, and if there isn’t much interest, I will close it. I’m not sure css-db should be too linked to PostCSS, so that it may pivot as Houdini becomes more of a thing.

This isn’t to say Houdini will make PostCSS irrelevant. More like, the whole ecosystem will evolve, converge, merge; who knows how.
