### ISSUE TITLE
Stages key?

### ISSUE THREAD

**Issue by miketaylr** [jonathantneal/css-db#2]
What does `NR` mean? Can there be some kind of Stage key? I clicked on "What are the stages?" but that didn't explain what NR meant.

(It's possible that this is some kind of unimplemented/early state, in which case, feel free to close the issue!)

<img width="1920" alt="screen shot 2017-02-16 at 12 44 32 pm" src="https://cloud.githubusercontent.com/assets/67283/23035728/bddaf248-f445-11e6-8ffc-c9cfcece610c.png">

**Comment by jonathantneal** [comment]
Legit bug, @miketaylr.

Until this repo knows better, every feature is marked "*Unrecognized*". Well, design-wise that word is way too long to put in the **Stage** column (otherwise 0 - 4). I need to give "Unrecognized" a better shorthand name, because "NR" ("*Not Recognized?*") is terrible.

And then I need to include a stage key **on this page**, at least while *everything* is marked as unrecognized.

**Comment by jonathantneal** [comment]
How do you feel about what’s been done here? https://jonathantneal.github.io/css-db/ + https://github.com/jonathantneal/css-db#no-stage-unrecognized

**Comment by miketaylr** [comment]
nice!
